 main: de.peacepunkt.mcpvpminigame.Main
 name: PVPMinigame
 version: 1.0
 author: Rossi
 description: pvp minigame
 api-version: 1.16

 commands:
   warp:
     description: warp to another world (must be loaded though)
     usage: /warp <worldname>
     permission: op
     permission-message: Nope..

