 main: de.peacepunkt.mcpvpminigame.Main
 name: PVPMinigame
 version: 1.0
 author: Rossi
 description: pvp minigame
 api-version: 1.16

 commands:
   warp:
     description: warp to another world (must be loaded though)
     usage: /warp <worldname>
     permission: op
     permission-message: Nope..

   start:
     description: start a round
     usage: /start
     permission: op
     permission-message: Nope..

   stop:
     description: stop a round
     usage: /stop
     permission: op
     permission-message: Nope..

   maketeam:
     description: create a team
     usage: /maketeam <name> <short_name> <leader name> <int>
     permission: op
     permission-message: Nope..

   position:
     description: warp to another world (must be loaded though)
     usage: /warp <worldname>
     permission: op
     permission-message: Nope..

   deleteTeam:
     description: deletes team of a leader
     usage: /deleteTeam <leader name>
     permission: op
     permission-message: Nope..

   invite:
     description: invite players to your team
     usage: /invite <player name>
     permission: leader
     permission-message: You do not lead a team

   accept:
     description: accept an invitation to a team

   deny:
     description: deny an invitaion to a team

   a:
     description: write in global chat
   trade:
     description: open trade gui
   newround:
     permission: op
     permission-message: Nope..
